---
- hosts: ubuntu
  vars:
    apt_key_dir: roles/ubuntuPreparation/files/apt_keys
    deb_files: roles/ubuntuPreparation/files
  pre_tasks:
     - name: Copy GPG keys
       synchronize:
         src: "{{ apt_key_dir }}"
         dest: /tmp/

    #  - name: Add apt keys
    #    apt_key:
    #      date: "{{ lookup('file', '{{ item.src }}') }}"
    #      state: present
    #    with_filetree: "{{ apt_key_dir }}/"
    #    when: item.state == 'file'
    
     - name: Add apt keys
       shell: cd /tmp/apt_keys && apt-key add *
       args:
        executable: /bin/bash
        warn: false

     - name: Rename sources.list file
       shell: "mv /etc/apt/sources.list /etc/apt/sources.list.disabled"
       args:
        executable: /bin/bash
        warn: false

     - name: Remove tmp directory
       changed_when: false
       file:
         path: "/tmp/apt_keys"
         state: absent

     - name: Change sources.list file
       changed_when: false
       copy:
         src: roles/ubuntuPreparation/files/lanartifactory_focal_sources.list
         dest: "/etc/apt/source.list.d/"

     - name: Run "apt-get update"
       apt:
        update_cache: yes

  roles:
    - ubuntuPreparation
