---
# vars file for test
requirement_packages:
  - vim
  - git
  - python3
  - python3-pip
  - terminator
  - tmux
  - tree
  - neovim
  - xpad
  - zsh
  - vlc
  - build-essential
  - gcc
  - remmina
  - remmina-plugin-*
  - ca-certificates
  - openjdk-11-jdk
  - simplescreenrecorder
  - kazam
  - unrar
  - zip
  - unzip
  - p7zip-full
  - p7zip-rar
  - rar
  - dnsutils
  - okular
  - filezilla
  - zim
  - sshpass
  - openssl
  - mosh
  - traceroute
  - virtualbox
  - curl
  - ipython3
  - openssh-server
  - openssh-client
  - gnupg-agent
  - software-properties-common
  - apt-transport-https
  - qemu-kvm
  - virtinst
  - virt-viewer
  - virt-manager
  - bridge-utils
  - cpu-checker
  - spice-client-gtk
  - fonts-farsiweb
  - mtr-tiny
  - htop
  - virt-top
  - imvirt
  - apg
  - at
  - bc
  - rsync
  - ftp
  - guake
  - x11vnc
  - clipit
  - cups-pdf
  - openvpn
  - network-manager-openvpn
  - gnome-tweaks
  - network-manager-openvpn-gnome
  - network-manager-vpnc
  - network-manager-l2tp
  - network-manager-l2tp-gnome
  - mlocate
  - net-tools
  - fonts-powerline
  - zsh-syntax-highlighting
  - ubuntu-restricted-extras
  - packer
  - bpython
  - ansible
  - xchm
  - spyder3
  - xrdp
  - i3
  - i3status
  - dmenu
  - i3lock
  - xbacklight
  - feh
  - conky
  - powerline
  - code
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - wine
  - winetricks
  - dos2unix
  # - kubectl
  # - chromium-browser