---
- name: "Install Docker"
  block:
    - name: "Uninstall unofficial Docker packages"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        autoremove: true
      loop: "{{ docker.packages.unofficial }}"

    - name: "Get Docker GPG"
      ansible.builtin.get_url:
        url: "{{ docker.release.url }}/{{ docker.release.gpg.file_name }}"
        dest: "{{ docker.release.gpg.temp_file_path }}"
        checksum: "{{ docker.release.gpg.checksum_hash }}"

    - name: "Generate Docker keyrings dearmor"
      ansible.builtin.shell: "gpg --dearmor < {{ docker.release.gpg.temp_file_path }} > {{ docker.release.gpg.archive_keyrings_path }}"
      no_log: true
      args:
        creates: "{{ docker.release.gpg.archive_keyrings_path }}"

    - name: "Add/Update Docker apt source list"
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }} signed-by={{ docker.release.gpg.archive_keyrings_path }}] {{ docker.release.url }} {{ ansible_distribution_release|lower }} {{ docker.release.name }}"
        state: present
        filename: "docker"
        update_cache: true

    - name: "Install official docker packages"
      ansible.builtin.apt:
        name: "{{ item }}={{ docker.release.version|default('*') }}"
        state: present
        update_cache: false
        install_recommends: false
      loop: "{{ docker.packages.official }}"
  notify: "restart-docker"
  tags:
    - "install-docker"

...