---
- name: "Get hashicorp keyring"
  block:
    - name: "Get hashicorp GPG"
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"

    - name: "Add/Update apt hashicorp repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: "hashicorp.list"
        update_cache: true
  tags:
    - "hashicorp-apt-repository"

...