---

- name: "Import prerequisites"
  import_tasks: "prerequisites.yml"

- name: "Import pip_install"
  import_tasks: "pip_install.yml"

- name: "Import libvirt_qemu"
  import_tasks: "libvirt_qemu.yml"

- name: "Import hashicorp_apt_repository"
  import_tasks: "hashicorp_apt_repository.yml"

- name: "Import googlechrome"
  import_tasks: "googlechrome.yml"
...