---

- name: "Import prerequisites"
  import_tasks: "prerequisites.yml"

- name: "Import pip_install"
  import_tasks: "pip_install.yml"

- name: "Import libvirt_qemu"
  import_tasks: "libvirt_qemu.yml"
...