---

- name: "Create '~/.config/pip/'"
  ansible.builtin.file:
    path: "/home/{{ mydesktop.system.username }}/.config/pip"
    owner: "{{ mydesktop.system.username }}"
    group: "{{ mydesktop.system.username }}"
    mode: "755"
    state: "directory"
  tags:
    - "prerequisites"
    - "pip-packages-list"

- name: "Add/Update pip in {{ mydesktop.system.username }}'s home dir"
  changed_when: false
  ansible.builtin.template:
    src: "pip.conf.j2"
    dest: "/home/{{ mydesktop.system.username }}/.config/pip/pip.conf"
    owner: "{{ mydesktop.system.username }}"
    group: "{{ mydesktop.system.username }}"
    mode: "0644"
  tags:
    - "prerequisites"
    - "pip-packages-list"

- name: "Install 'pip_packages_list'"
  become: false
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ pip_packages_list }}"
  tags:
    - "prerequisites"
    - "pip-packages-list"
...