---
- name: "Run apt-get update"
  ansible.builtin.apt:
    update_cache: true
  tags:
    - "prerequisites"

- name: "Install 'display_server_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ display_server_packages_list }}"
  register: display_server_installation
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "display-server-packages-list"

- name: "Install 'system_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ system_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "system-packages-list"

- name: "Install 'python_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ python_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "python-packages-list"

- name: "Install 'pip_packages_list'"
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ pip_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "pip-packages-list"

- name: "Install 'security_management_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ security_management_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "security-management-packages-list"

- name: "Install 'gpg_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ gpg_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "gpg-packages-list"

- name: "Install 'ssh_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ ssh_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "ssh-packages-list"

- name: "Install 'network_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ network_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "network-packages-list"

- name: "Install 'compression_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ compression_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "compression-packages-list"

- name: "Install 'sound_management_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ sound_management_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "sound-management-packages-list"

- name: "Install 'system_utility_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ system_utility_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "system-utility-packages-list"

- name: "Install 'essential_font_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ essential_font_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "essential-font-packages-list"

- name: "Install 'editor_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ editor_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "editor-packages-list"

- name: "Install 'file_manager_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ file_manager_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "file-manager-packages-list"

- name: "Install 'terminal_emulator_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ terminal_emulator_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "terminal-emulator-packages-list"

- name: "Install 'screen_capture_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ screen_capture_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "screen-capture-packages-list"

- name: "Install 'remote_desktop_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ remote_desktop_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "remote-desktop-packages-list"

- name: "Install 'clipboard_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ clipboard_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "clipboard-packages-list"

- name: "Install 'internet_utility_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ internet_utility_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "internet-utility-packages-list"

- name: "Install 'bluetooth_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ bluetooth_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "bluetooth-packages-list"

- name: "Install 'vpn_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ vpn_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "vpn-packages-list"

- name: "Install 'pdf_management_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ pdf_management_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "pdf-management-packages-list"

- name: "Install 'media_player_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ media_player_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "media-player-packages-list"

- name: "Install 'libvirt_qemu_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ libvirt_qemu_packages_list }}"
  #  notify: sudo sudo systemctl is-active libvirtd
  #  sudo usermod -aG libvirt $USER
  #  sudo usermod -aG kvm $USER
  #  $ cat /etc/nsswitch.conf
  #  # /etc/nsswitch.conf:
  #  hosts: files libvirt libvirt_guest dn
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "libvirt-qemu-packages-list"

- name: "Install 'system_events_notifications_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ system_events_notifications_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "system-events-notifications-packages-list"

- name: "Install 'printer_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ printer_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "printer-packages-list"

- name: "Install 'mail_client_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ mail_client_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "mail-client-packages-list"

- name: "Install 'minimal_desktop_environment_packages_list'"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: false
    install_recommends: true
  loop: "{{ minimal_desktop_environment_packages_list }}"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "minimal-desktop-environment-packages-list"

- name: "Restart/Active installed services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  loop:
    - "libvirtd"
    - "cups"
    - "bluetooth"
    - "lightdm"
    - "avahi-daemon"
    - "acpid"
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "restart-essential-services"

- name: "Reboot the host"
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to display server installation/updates"
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when:
    - display_server_installation.changed
    - not ansible_connection == 'local'
    - not ansible_check_mode
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "prerequisites-reboot"

- name: "Finish the playbook"
  block:
    - name: "Print message"
      ansible.builtin.debug:
        msg:
          - "Since the playbook is running on local connection, and display_server_installation has been changed."
          - "Please reboot the host and proceed with the playbook"

    - name: "Stop the playbook"
      ansible.builtin.meta: end_play
      when:
        - not ansible_check_mode
  when:
    - ansible_connection == 'local'
    - not ansible_check_mode
  tags:
    - "prerequisites"
    - "prerequisites-install"
    - "prerequisites-reboot"

...