---

- name: "Manipulate docker-credential-helper variables"
  set_fact:
    docker_credential_release_url: "{{ docker.credential.release.url }}"
    docker_credential_version: "{{ docker.credential.release.version }}"
    docker_credential_artifact_name: "docker-credential-pass-{{ docker.credential.release.version }}.linux-{{ my_desktop_architecture }}"
  tags:
    - always

- name: "Install docker-credential-helper"
  ansible.builtin.get_url:
    url: "{{ docker_credential_release_url }}/download/{{ docker_credential_version }}/{{ docker_credential_artifact_name }}"
    dest: "/usr/local/bin/docker-credential-pass"
    checksum: "{{ docker.credential.release.checksum_hash }}"
    mode: "0755"
  tags:
    - "configure-docker"
    - "docker-credential"
...