---
- name: "Setup My Desktop"
  hosts: myDesktop
  strategy: free
  gather_facts: true
  become: true
  environment:
    PIP_REQUIRE_VIRTUALENV: false
  roles:
    - { role: "prerequisites" }
    - { role: "docker" }
    - { role: "k8s_utilities" }

...