---
ansible_connection: "ssh"
prerequisite_packages_list: []
utility_packages: []


mydesktop:
  user:
    first_name: "Vagrant"
    last_name: "Vagrant"
    email_address: "vagrant@vagrant.org"

  system:
    username: "vagrant"
    hostname: "mydesktop"
    default_editor: "vim"
    display_server: "xorg"
    display_manager: "lightdm"
    display_windows_manager: "i3" #awesome,qtile

pipconf:
    global_timeout: 60
    global_quiet: 0
    global_verbose: 2
    global_break_system_packages: true
    global_require_virtualenv: true
    global_download_cache: /tmp
    global_log_file: /tmp/pip-log.txt
    freeze_timeout: 10

virtualization:
  libvirt_qemu: true
  virtualbox: false

deb_architecture: {
  "aarch64": "arm64",
  "x86_64": "amd64"
}

# Hashicorp Official Packaging Guide:
# https://www.hashicorp.com/official-packaging-guide
# https://www.hashicorp.com/security
hashicorp:
  archive_keyrings_path: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
  gpg_checksum: "sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029" # curl -sL https://apt.releases.hashicorp.com/gpg|sha256sum
  release_url: "https://apt.releases.hashicorp.com"

googlechrome:
  archive_keyrings_path: "/usr/share/keyrings/google-chrome-archive-keyring.gpg"
  gpg_checksum: "sha256:fb8df9740df6a1125fd2983465d830b764b63cd92d5ada8b5bbf75927d6a71ee" # curl -sL https://dl.google.com/linux/linux_signing_key.pub|sha256sum
  gpg_key_url: "https://dl.google.com/linux/linux_signing_key.pub"
  release_url: "https://dl.google.com/linux/chrome/deb/"
  package_name: "google-chrome-stable"

# https://wiki.debian.org/JetBrains
intellij_idea:
  archive_keyrings_path: "/usr/share/keyrings/jetbrains-archive-keyring.gpg"
  package_name: "intellij-idea-community"
  release_url: "http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com"
  gpg_key_url: "https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc"
  gpg_checksum: "sha256:a8eeb391e6cdc8090c149887a55c416c43486b7d6e78ea6f9e7096d403233359" # curl -sL https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc|sha256sum

# https://code.visualstudio.com/docs/setup/linux
vscode:
  archive_keyrings_path: "/usr/share/keyrings/vscode-archive-keyring.gpg"
  package_name: "code"
  release_url: "https://packages.microsoft.com/repos/code"
  gpg_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
  gpg_checksum: "sha256:2cfd20a306b2fa5e25522d78f2ef50a1f429d35fd30bd983e2ebffc2b80944fa" # curl -sL https://packages.microsoft.com/keys/microsoft.asc|sha256sum


...