---
ansible_connection: "ssh"
prerequisite_packages_list: []
utility_packages: []


mydesktop:
  user:
    first_name: "Vagrant"
    last_name: "Vagrant"
    email_address: "vagrant@vagrant.org"

  system:
    username: "vagrant"
    hostname: "mydesktop"
    default_editor: "vim"
    display_server: "xorg"
    display_manager: "lightdm"
    display_windows_manager: "i3" #awesome,qtile

pipconf:
    global_timeout: 60
    global_quiet: 0
    global_verbose: 2
    global_break_system_packages: true
    global_require_virtualenv: true
    global_download_cache: /tmp
    global_log_file: /tmp/pip-log.txt
    freeze_timeout: 10

virtualization:
  libvirt_qemu: true
  virtualbox: false

deb_architecture: {
  "aarch64": "arm64",
  "x86_64": "amd64"
}

# Hashicorp Official Packaging Guide:
# https://www.hashicorp.com/official-packaging-guide
# https://www.hashicorp.com/security
hashicorp:
  release_url: "https://apt.releases.hashicorp.com"
  archive_keyrings_path: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
  finger_print: "798AEC654E5C15428C8E42EEAA16FCBCA621E701"
  gpg_checksum: "sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029"
  
...