---

prerequisite_packages_list:
  - "vim"
  - "git"
  - "python3"
  - "python3-pip"
  - "terminator"
  - "tmux"
  - "tree"
  - "gcc"
  - "xpad"
  - "vlc"
  - "build-essential"
  - "remmina"
  - "remmina-plugin-*"
  - "ca-certificates"
  - "simplescreenrecorder"
  - "kazam"
  - "unrar"
  - "rar"
  - "zip"
  - "unzip"
  - "p7zip-full"
  - "p7zip-rar"
  - "dnsutils"
  - "okular"
  - "filezilla"
  - "zim"
  - "sshpass"
  - "openssl"
  - "mosh"
  - "traceroute"
  - "virtualbox"
  - "curl"
  - "ipython3"
  - "openssh-server"
  - "openssh-client"
  - "gnupg-agent"
  - "software-properties-common"
  - "apt-transport-https"
  - "qemu-kvm"
  - "virtinst"
  - "virt-viewer"
  - "virt-manager"
  - "bridge-utils"
  - "cpu-checker"
  - "spice-client-gtk"
  - "mtr-tiny"
  - "htop"
  - "virt-top"
  - "imvirt"
  - "apg"
  - "at"
  - "bc"
  - "rsync"
  - "ftp"
  - "x11vnc"
  - "cups-pdf"
  - "openvpn"
  - "network-manager-openvpn"
  - "network-manager-vpnc"
  - "network-manager-l2tp"
  - "fonts-farsiweb"
  - "net-tools"
  - "mlocate"
  - gnome-tweaks
  - network-manager-l2tp-gnome
  - network-manager-openvpn-gnome
  - clipit
  - fonts-powerline
  - guake
  - neovim
  - zsh-syntax-highlighting
  - ubuntu-restricted-extras
  - "packer"
  - bpython
  - ansible
  - xchm
  - spyder3
  - xrdp
  - i3
  - i3status
  - dmenu
  - i3lock
  - xbacklight
  - feh
  - conky
  - "powerline"
  - "code"
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
  - "dos2unix"
  - "zstd"
  - "xsel"
  - "aria2"
  - "copyq-plugins"
  - "copyq"
  - "discord"
  - "dnsmasq"
  - "flatpak"
  - "kdenlive"
  - kubectl
  - "openconnect"
  - "ifupdown"
  - "git"
  - "curl"
  - "unzip"
  - "apt-transport-https"
  - "make"
  - "libfontconfig"
  - "g++"
  - "chromium"
  - "mutt"
  - "ttf-mscorefonts-installer"
  - "jq"
  - "ruby"
  - "nmap"
  - "libatk-bridge2.0-0"
  - "libgtk-3-0"
  - "python3"
  - "rsync"
  - "libjemalloc2"
  - "python3-virtualenv"
  - "virtualenv"
  - "libldap2-dev"
  - "libsasl2-dev"
  - "qemu"
  - "ksmtuned"
  - "qemu-kvm"
  - "ksmtuned"
